version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./model:/app/model"
      - "./data:/app/data"
    environment:
      - MODEL_NAME=siebert/sentiment-roberta-large-english
      - MODEL_FRAMEWORK=pytorch
      - ENABLE_QUANTIZATION=false
      - ENABLE_HOT_RELOAD=true
      - DEBUG=false
      - CORS_ORIGINS=["http://localhost:3000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  backend-gpu:
    profiles: ["gpu"]
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "8000:8000"
    volumes:
      - "./model:/app/model"
      - "./data:/app/data"
    environment:
      - MODEL_NAME=siebert/sentiment-roberta-large-english
      - MODEL_FRAMEWORK=pytorch
      - DEVICE=cuda
      - ENABLE_QUANTIZATION=true
      - QUANTIZATION_BACKEND=tensorrt
      - ENABLE_HOT_RELOAD=true
      - DEBUG=false
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Optional: Redis for caching (future enhancement)
  redis:
    profiles: ["cache"]
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
